### ISSUE TITLE
Need to change connection details

### ISSUE THREAD

**Issue by PhilStollery** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Download the python demo, add credentials and try to run it

### Any log messages given by the failure
>There was an exception: module 'gremlin_python.driver.serializer' has no attribute 'GraphSONSerializersV2d0'

### Expected/desired behavior
>The program to run without errors

### OS and Version?
> Windows 10

### Versions
> Latest

### Mention any other details that might be useful

The fix is to change line 107 from:
message_serializer=serializer.GraphSONSerializersV2d0()
to
 message_serializer=serializer.GraphSONMessageSerializer()

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kasiaul** [comment]
Thank you for 'GraphSONMessageSerializer()'

**Comment by olivertowers** [comment]
Latest version of the sample requires `GraphSONSerializersV2d0()` and works in it's latest form.
