### ISSUE TITLE
Is there a reason you're not using gremlinpython?

### ISSUE THREAD

**Issue by aronchick** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
This code sets up trivial SQL injection. Should really use gremlinpython.

**Comment by olivertowers** [comment]
The sample uses gremlin-python which can issue script requests with parameterized queries which will prevent injection attacks for client apps. However, the sample doesn't give an example of using this so created issue #26 to track updating the sample.
