### ISSUE TITLE
unable to iterate through dict (or parse any variables in g.addV request)

### ISSUE THREAD

**Issue by marlon-montgomery** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
unable to reference any kind of variable or dict value in gremlin

with open('/Users/marlon.montgomery/Documents/GitHub/azure-cosmos-db-graph-python-getting-started/Connections.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        fullName = first_name + " " + last_name
        _gremlin_insert_vertices = "g.addV('person').property('id',fullName).property('label', person).property('First Name', {first_name}).property('Last Name', {last_name}).property('Email Address', {email_address}).property('Company', {company}).property('Position', {position}).property('pk', 'pk')"
        callback = client.submitAsync(_gremlin_insert_vertices)
        print("\tInserted this vertex:\n\t{0}\n".format(
            callback.result().one()))

### Any log messages given by the failure
>
ActivityId : af234282-6394-4e45-87b2-1bf40e79f89d
ExceptionType : GraphMalformedException
ExceptionMessage :
        Gremlin Malformed Request: GraphSON v3 IO is not supported.
        GremlinRequestId : af234282-6394-4e45-87b2-1bf40e79f89d
        Context : global
        GraphInterOpStatusCode : MalformedRequest
        HResult : 0x80131500

### Expected/desired behavior
> Ability to iterate through dict or csv read

### OS and Version?
>  macOS Catalina 10.15.5

### Versions
 Python 3.6.1 64 bit
from gremlin_python.driver import client, serializer
import sys
import traceback
import csv

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by olivertowers** [comment]
Message Serializer needs to be set to GraphSON V2 per latest sample.
Also would recommend using parameter bindings for `client.submitAsync`
eg.
```
client.submitAsync("g.V().has(prop_a, prop_a_value)", { 'prop_a' : 'city', 'prop_a_value'  : 'Seattle' })
```
