### ISSUE TITLE
ERROR:asyncio:Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by pawankumar-stack** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#16]
I am getting below error after running the connect.py to connect to cosmosdb via gremlin in local emulator.

ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketProtocol13._receive_frame_loop() running at C:\Repository\Automation_CosmosDB\git-samples\azure-cosmos-db-graph-python-getting-started\venv\lib\site-packages\tornado\websocket.py:1118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001DDF11E8168>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Repository\Automation_CosmosDB\git-samples\azure-cosmos-db-graph-python-getting-started\venv\lib\site-packages\tornado\ioloop.py:690]>

Python version : 3.6.5
gremlinpython : 3.2.7
tornado :6.0.4
OS : Windows10

can you please help me on this?
Thanks

**Comment by olivertowers** [comment]
This was for an older version of gremlinpython and it's not clear on the connection string used. Latest sample seems to work as expected with emulator with Gremlin API enabled.
