### ISSUE TITLE
connect.py fails at insert_vertices(client) with  **AttributeError: 'NoneType' object has no attribute 'decode'**

### ISSUE THREAD

**Issue by adrpino** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have created a trial account, followed [tutorial here](https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-python) and run script. I understand that the failure is caused by no data being returned. What I would like to know is what's the failure reason.
When I inspect (from `ipdb`) the `callback.result().__dict__` (to observe its inner elements), I get:

    ipdb> callback.result().__dict__
    {'_done': <Future at 0x7ffbb01c2da0 state=finished raised AttributeError>, '_stream': <queue.Queue object at 0x7ffbb01b10f0>, '_request_id': 'a61f61f7-2a69-4d7b-9a08-5a6b4dcc76db', '_aggregate_to': None}

So it's basically finished with an `AttributeError`.

### Any log messages given by the failure
> ---------------------------------------------------------------------------
```
AttributeError                            Traceback (most recent call last)
~/azure-cosmos-db-graph-python-getting-started/connect.py in <module>()
    113 # Insert all vertices
    114 input("Let's insert some vertices into the graph. Press any key to continue...")
--> 115 insert_vertices(cl)
    116 
    117 # Create edges between vertices

~/azure-cosmos-db-graph-python-getting-started/connect.py in insert_vertices(client)
     49         callback = client.submitAsync(query)
     50         if callback.result() is not None:
---> 51             print("\tInserted this vertex:\n\t{0}\n".format(callback.result().one()))
     52         else:
     53             print("Something went wrong with this query: {0}".format(query))

~/badi/badi_env/lib/python3.5/site-packages/gremlin_python/driver/resultset.py in one(self)
     72         if not self.stream.empty():
     73             return self.stream.get_nowait()
---> 74         return self.done.result()
     75 
     76     def all(self):

/usr/lib/python3.5/concurrent/futures/_base.py in result(self, timeout)
    396                 raise CancelledError()
    397             elif self._state == FINISHED:
--> 398                 return self.__get_result()
    399 
    400             self._condition.wait(timeout)

/usr/lib/python3.5/concurrent/futures/_base.py in __get_result(self)
    355     def __get_result(self):
    356         if self._exception:
--> 357             raise self._exception
    358         else:
    359             return self._result

/usr/lib/python3.5/concurrent/futures/thread.py in run(self)
     53 
     54         try:
---> 55             result = self.fn(*self.args, **self.kwargs)
     56         except BaseException as e:
     57             self.future.set_exception(e)

~/badi/badi_env/lib/python3.5/site-packages/gremlin_python/driver/connection.py in _receive(self)
     75     def _receive(self):
     76         data = self._transport.read()
---> 77         self._protocol.data_received(data, self._results)
     78         self._pool.put_nowait(self)

~/badi/badi_env/lib/python3.5/site-packages/gremlin_python/driver/protocol.py in data_received(self, data, results_dict)
     67 
     68     def data_received(self, data, results_dict):
---> 69         data = json.loads(data.decode('utf-8'))
     70         request_id = data['requestId']
     71         result_set = results_dict[request_id]

AttributeError: 'NoneType' object has no attribute 'decode'
```

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by AxoSal** [comment]
Any solution to this?

**Comment by kealin** [comment]
Also encountering this issue. Unable to query from Python. Filtered out external issues by testing similar logic in gremlin console & nodejs app.

**Comment by adrpino** [comment]
Hi @AxoSal and @kealin . We ended up tailoring the `gremlin-python` package used to handle the AttributeError provided. 

The issue (I don't have it very fresh since we discarded the technology due to the lack of support) was that the provided version of `gremlin-python` didn't talk the same serialization protocol as Gremlin server that may be behind the CosmosDB service.  We used `gremlin-python` version `3.2.6` and modified it's source code to handle the error on the point where the exception was raised.

**Comment by jgtech** [comment]
Also receiving this same error.  
I tried updating to gremlinpython==3.3**.1** version from the default 3.3**.0** Same error again.

**Comment by AxoSal** [comment]
@adrpino what did you switch to?

**Comment by LuisBosquez** [comment]
Hello everyone. This error indicates that you're using the Python application against a preview Cosmos DB Graph account (basically one that was created before December 20th). The Python compatibility is only supported in the General Availability version of the graph account. A quick workaround is just to re-create your Graph account. Otherwise, please wait until we migrate all the accounts, which should be happening within the next few weeks.

**Comment by mcharters** [comment]
@LuisBosquez also getting the same error after creating a Cosmos DB Graph account created today in the Canada-East region. Is python just not available? How can we check whether or not our Cosmos dbs are "general availability"?

**Comment by andrewnippard** [comment]
Hi all,

I've had some success changing by changing the client's default message_serializer to GraphSONSerializersV2d0 - [default](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/jython/gremlin_python/driver/client.py) is GraphSONSerializersV3d0.

```python
from gremlin_python.driver import client, serializer

client = client.Client("wss://***.gremlin.cosmosdb.azure.com:443/","g",
   username="/dbs/***/colls/***",
   password="***",
   message_serializer=serializer.GraphSONSerializersV2d0()
)
```

**Comment by LuisBosquez** [comment]
Thanks everyone for raising this issue. I have added the fix to the sample.

**Comment by soderluk** [comment]
I'm still getting this issue, even with the fixes above. 
I have my own client class that I'm using, and running `g.V().drop()`  gives me the same `AttributeError: 'NoneType' object has no attribute 'decode'` error.

If I run the same script multiple times, it sometimes goes through on the second try, sometimes on the fifth try.

I then try to run this example, and the `g.V().drop()` goes through fine, but when running the next part:
```
Let's insert some vertices into the graph. Press any key to continue...
        Running this Gremlin query:
        g.addV('person').property('id', 'thomas').property('firstName', 'Thomas').property('age', 44)

There was an exception: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "connect.py", line 140, in <module>
    insert_vertices(client)
  File "connect.py", line 59, in insert_vertices
    callback.result().one()))
  File "/home/vagrant/.virtualenvs/setup_scripts/lib/python3.5/site-packages/gremlin_python/driver/resultset.py", line 74, in one
    return self.done.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vagrant/.virtualenvs/setup_scripts/lib/python3.5/site-packages/gremlin_python/driver/connection.py", line 77, in _receive
    self._protocol.data_received(data, self._results)
  File "/home/vagrant/.virtualenvs/setup_scripts/lib/python3.5/site-packages/gremlin_python/driver/protocol.py", line 69, in data_received
    data = json.loads(data.decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'
```
I get the same error again.

This is totally random, and I don't know what is causing this. Anyone else got the same problem still?
Using 
futures==3.1.1
gremlinpython==3.3.1

**Comment by kuldeepyadav** [comment]
I am facing the same issue. Created another issue since this is closed.
