### ISSUE TITLE
[Errno 10061] Unknown error is not helpful. 

### ISSUE THREAD

**Issue by BillmanH** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#21]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Something useful I can use in the `ConnectionRefusedError: [Errno 10061] Unknown error`
maybe a cryptic clue or something.

### Minimal steps to reproduce
> Just clone and run the code. I haven't gotten it to run successfully yet. 

I'm hoping you can give me some tips as to what to try in troubleshooting this issue. 
* Instnce is running and I can query it in tinkerpop. 
* I can access it from https://localhost:8081/_explorer/index.html
* It would be great to have some more detailed error messages. 
* Any tips you can give would be helpful. 

```python
client = client.Client('wss:/localhost:8901/', 'g',
						username="/dbs/db1/colls/coll1",
						password="pwd-from-site",
						message_serializer=serializer.GraphSONMessageSerializer()
						)
```
### Any log messages given by the failure
Full stack trace:
```
Welcome to Azure Cosmos DB + Gremlin on Python!
We're about to drop whatever graph is on the server. Press any key to continue...

> g.V().drop()
Traceback (most recent call last):
  File "connect.py", line 181, in <module>
    cleanup_graph(client)
  File "connect.py", line 58, in cleanup_graph
    callback = client.submitAsync(_gremlin_cleanup_graph)
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\client.py", line 148, in submitAsync
    return conn.write(message)
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\connection.py", line 55, in write
    self.connect()
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\connection.py", line 45, in connect
    self._transport.connect(self._url, self._headers)
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\tornado\transport.py", line 41, in connect
    lambda: websocket.websocket_connect(url, compression_options=self._compression_options))
  File "C:\Users\<user>\anaconda3\envs\npd\lib\site-packages\tornado\ioloop.py", line 576, in run_sync
    return future_cell[0].result()
ConnectionRefusedError: [Errno 10061] Unknown error
```

### Expected/desired behavior
> Not crash. Or if crashed, an error message that tells me what happened so that I can investigate. 

### OS and Version?
> Windows 10

### Versions
```
gremlinpython==3.4.8
futures
```

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by manishmsfte** [comment]
Thanks Bill for raising the issue. For connect Gremlin client with emulator please use ws://localhost:8901

**Comment by BillmanH** [comment]
Confirmed. This issue is a `s` requesting the secure connection, which is unavailable on localhost.
