### ISSUE TITLE
NotImplementedError  when running python connect.py

### ISSUE THREAD

**Issue by Nikolai-Master** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#22]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>As per the demo instructions (db setup in serverless mode)

### Any log messages given by the failure
>NotImplementedError 

### Expected/desired behavior
>I'd expect such a simple bit of demo code to work without cryptic error messages.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win10
### Versions
>

### Mention any other details that might be useful
It appears to be connection related. The code run until the cleanup_graph(client), then fails with the only error message "NotImplemented".  I've checked and re-checked the connection string details. They're definitely correct. Cosmos db setup db/collection name matches the names in the sample. 

client = client.Client('wss://mygraphaccount.gremlin.cosmos.azure.com:443/', 'g',
                           username="/dbs/sample-database/colls/sample-graph/",
                           password="*PRIVATEKEY*",
                           message_serializer=serializer.GraphSONSerializersV2d0()
                           )

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RSteeno** [comment]
I'm also running into this error.

**Comment by Nikolai-Master** [comment]
Fixed it. The requirements.txt contains a ref to the old versions of the library. Uninstall the first one. Run:
pip uninstall gremlinpython 
pip install gremlinpython
The first will uninstall 'gremlinpython==3.4.8' which causes the issue. Will be looking at AWS Neptune much more closely now.
