### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by andrewscul** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#24]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Just follow the documentation here:
https://docs.microsoft.com/en-us/azure/cosmos-db/graph/create-graph-python

### Any log messages given by the failure
>
Welcome to Azure Cosmos DB + Gremlin on Python!
We're about to drop whatever graph is on the server. Press any key to continue...

> g.V().drop()
Traceback (most recent call last):
  File "/azure-cosmos-db-graph-python-getting-started/connect.py", line 165, in <module>
    cleanup_graph(client)
  File "/azure-cosmos-db-graph-python-getting-started/connect.py", line 58, in cleanup_graph
    callback = client.submitAsync(_gremlin_cleanup_graph)
  File "/azure-cosmos-db-graph-python-getting-start-Z1k35egt/lib/python3.9/site-packages/gremlin_python/driver/client.py", line 146, in submitAsync
    return conn.write(message)
  File "/azure-cosmos-db-graph-python-getting-start-Z1k35egt/lib/python3.9/site-packages/gremlin_python/driver/connection.py", line 55, in write
    self.connect()
  File "/azure-cosmos-db-graph-python-getting-start-Z1k35egt/lib/python3.9/site-packages/gremlin_python/driver/connection.py", line 45, in connect
    self._transport.connect(self._url, self._headers)
  File "/azure-cosmos-db-graph-python-getting-start-Z1k35egt/lib/python3.9/site-packages/gremlin_python/driver/tornado/transport.py", line 35, in connect
    self._ws = self._loop.run_sync(
  File "/azure-cosmos-db-graph-python-getting-start-Z1k35egt/lib/python3.9/site-packages/tornado/ioloop.py", line 576, in run_sync
    return future_cell[0].result()
ConnectionRefusedError: [Errno 61] Connection refused

### Expected/desired behavior
>
A connection to the database.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10, MacOS Monterey and a basic Docker Python container.

### Versions
>
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
gremlinpython = "==3.4.8"
futures = "*"

[dev-packages]

[requires]
python_version = "3.9"

### Mention any other details that might be useful
The documentation includes:
client = client.Client('wss://test.gremlin.cosmosdb.azure.com:443/','g', 
    username="/dbs/<YOUR_DATABASE>/colls/<YOUR_COLLECTION_OR_GRAPH>", 
    password="<YOUR_PASSWORD>")

Note the path includes: 
gremlin.cosmosdb.azure.com:443/

Yet the Azure portal has the endpoint listed as: 
gremlin.cosmos.azure.com:443/

Note the missing db on cosmos
This inconsistency does not help, however, I have tried both and both produce the same error.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by olivertowers** [comment]
@andrewscul  - did this issue get resolved?
If not, Connection refused is a very broad error so any additional details will be helpful. Things to try:
1. Can you use Azure Portal gremlin data explorer from the same machine you are running python ? If this works it suggests that your machine can reach the endpoint so there might be some issue in python itself.
2. Recommended version for gremlin-python is now 3.4.13 which did make some significant changes, including using a different websocket library, so would also recommend updating to this version.

**Comment by olivertowers** [comment]
Closing issue as there has been no further updates.
