### ISSUE TITLE
replace graphs.azure.com with gremlin.cosmosdb.azure.com

### ISSUE THREAD

**Issue by AxoSal** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#3]
### This issue is for:
- [x ] documentation issue or request

When you run python connect.py with graphs.azure.com as endpoint you get an error. I spotted that the Azure team has changed the URL to gremlin.cosmosdb.azure.com. This repo should represent that.

Also, regarding the "collection name"... I'm a new to Azure and databases in general. I couldn't find collection name in the Azure portal, but as I remember that I named everything the same. It worked well this time. But maybe an explanation of where or how you can find the collection name would be helpful.

**Comment by LuisBosquez** [comment]
Thanks for reporting @AxoSal!

We have in fact changed the URL endpoint to gremlin.cosmosdb.azure.com. For reference, the collection name is also known as the "Graph" name, which is what you assign RU/s to. 

An account can have many databases, and each database can have many collections/graphs. The name of the lowest level item should be what you're looking for.

Thanks,
Luis
